### ISSUE TITLE
Add board game algos Like Tic Tac Toe, Connect 4, Ludo, Snakes and Ladder etc...

### ISSUE THREAD

**Issue by M-Usman-Tahir** [Bit-ByBit/Board-Games#1]
# Board-Games

## What to do...
Add Board games like Tic Tac Toe, Connect 4, Ludo, Snakes and Ladder, etc...

## How to do...
- Fork the repo
- Clone the repo  
```
git clone https://github.com/Bit-ByBit/Board-Games
```
- Make a directory of the name of your game in the directory of the language you will be using.
- Push the code  
```
git add .  
git commit -m "ALGO-NAME Contribution"
git push -u origin YOUR-USERNAME
```

It is a good first issue 🌟

**Comment by Prashant0kgp** [comment]
plz, assign me I want to add my brickout game under hacktoberfest labels.
it's my 1st game in JS!
thank you!

**Comment by M-Usman-Tahir** [comment]
@jyotijangid You can work on it...

**Comment by dayanand-g** [comment]
can you just please assign me to this issue. I want to add my snake game.
please help me out, this is my first open source,
Thank you

**Comment by Hammad-001** [comment]
I want to work on snakes and ladder...
Assign me!!!

**Comment by ABHISHEK-565** [comment]
hey i would like to add tic tac toe game in kotlin can you assign me that

**Comment by ij943** [comment]
I will add Tic Tac Toe please assign me the task.

**Comment by AbdulQadir-6411** [comment]
Assign me for tic tac toe
